### ISSUE TITLE
Protótipo da Aplicação[Versão1.0]

### ISSUE THREAD

**Issue by Danpam12** [davifurao/Energy-Monitor#10]
Link do Figma  para o protótipo do Energy Monitor.

https://www.figma.com/file/JbxHpKTaaN9YW4T1jep6Xi/Monitor-Energy?node-id=0%3A1&t=5wi5IOnb1dR10chx-1

**Comment by davisouzaluna** [comment]
Protótipo que expressa o fluxo da aplicação e como será a regra de negócio da mesma feito, portanto estamos na versão 1.0 em 07/05/2023
